// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rate.proto

package org.hps;

public interface RateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rateresponse = 1;</code>
   * @return The rateresponse.
   */
  String getRateresponse();
  /**
   * <code>string rateresponse = 1;</code>
   * @return The bytes for rateresponse.
   */
  com.google.protobuf.ByteString
      getRateresponseBytes();
}
