// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rate.proto

package org.hps;

public interface RateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string raterequest = 1;</code>
   * @return The raterequest.
   */
  String getRaterequest();
  /**
   * <code>string raterequest = 1;</code>
   * @return The bytes for raterequest.
   */
  com.google.protobuf.ByteString
      getRaterequestBytes();
}
